Repository khattakdev/capture, pull requests merged in 2023-10, with the labels that each got.

#9 add keybindings to take snap
  package.json
Labels: hacktoberfest

#17 feat: Show error on no selection
  src/extension.ts
Labels: enhancement, hacktoberfest

#20 feat: Add theme support
  package.json
  src/extension.ts
  src/template.ts
Labels: hacktoberfest, hacktoberfest-accepted

#10 🚀 Added image opening functionality
  src/extension.ts
Labels: hacktoberfest-accepted

#25 Added Discord link in Readme | Issue #24
  README.md
Labels: hacktoberfest-accepted
